name: Lint Code Base

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ruff checking
        uses: astral-sh/ruff-action@v3
        with:
          version: ">=0.11.10,<0.12.0"

      - run: ruff check
      - run: ruff format --check --diff